# Generated by Django 5.0.6 on 2025-02-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subscription_order_id_alter_subscription_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='plan',
            field=models.CharField(default='noplan', max_length=100),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
