# Generated by Django 5.0.6 on 2025-02-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_workoutvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymuser',
            old_name='mobile',
            new_name='number',
        ),
    ]
