# Generated by Django 5.0.6 on 2025-02-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_trainermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermessage',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='myapp.gymuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='myapp.gymuser'),
        ),
    ]
