# Generated by Django 5.0.6 on 2025-02-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_trainermessage_trainer_alter_trainermessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='goal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gymuser',
            name='trainer_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.gymuser'),
        ),
    ]
