# Generated by Django 5.0.6 on 2025-02-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_gymuser_goal_gymuser_trainer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymuser',
            old_name='trainer_id',
            new_name='trainer',
        ),
    ]
